from django.db.models import Count

from qncy.models import Tag
from core.models import User


# This is temporary, as both blocks will eventually be generated by a script.
# And we do not fully conform to the spec (e.g. we don't check upload time)
def common_context(request):
    top_tags = Tag.objects.annotate(uses=Count("question")).order_by("-uses")[:20]
    top_users = User.objects.order_by("-rating")[:10]

    return {"common": {"top_tags": top_tags, "top_users": top_users}}
